# XTB Login
XTB_USER_ID = 51593558
XTB_PASSWORD = "DEIN_PASSWORT"
XTB_SERVER = "real"

# Telegram Bot
TELEGRAM_TOKEN = "DEIN_BOT_TOKEN"
TELEGRAM_CHAT_ID = "DEINE_CHAT_ID"

# Symbol
NATGAS_SYMBOL = "NATGAS"
